import { z } from "../openapi";

export const workspaceIdParam = z.object({ workspaceId: z.string() });

export const workspaceMembersQuery = z.object({
  include: z.enum(["projects"]).optional().openapi({
    description:
      'Pass "projects" to add `projects` and `fullAccess` to every member. Only a caller who manages members (workspace role with member:create, member:update or member:delete) or has full access gets them; for anybody else the parameter has no effect.',
  }),
});

export const userDirectoryQuery = z.object({
  q: z.string().max(100).openapi({
    description:
      "Part of a name or email address, at least 2 characters after trimming.",
  }),
});

export const addWorkspaceMemberBody = z.object({
  userId: z.string().min(1).openapi({
    description:
      "An existing account of this instance that is not a member of the workspace yet (find it with the user directory).",
  }),
  role: z.string().min(1).openapi({
    description:
      "The workspace role to grant: the built-in viewer, member or admin, or a custom role. owner is never allowed, and every permission of the role must also be held by the caller (owners and instance administrators may grant any role except owner).",
  }),
});

const pagingNumber = (min: number, max: number) =>
  z
    .string()
    .regex(/^\d+$/, "Expected a positive integer")
    .transform(Number)
    .pipe(z.number().int().min(min).max(max));

// Required object of optional filters: a RouteParameter cannot itself be optional.
export const workspaceActivityQuery = z.object({
  userId: z.string().optional().openapi({
    description: "Only activity generated by this user.",
  }),
  type: z.string().optional().openapi({
    description: "Only activity of this type, e.g. status_changed.",
  }),
  projectId: z.string().optional().openapi({
    description: "Only activity on tasks belonging to this project.",
  }),
  from: z.string().optional().openapi({
    description: "Only activity created at or after this ISO timestamp.",
  }),
  to: z.string().optional().openapi({
    description: "Only activity created at or before this ISO timestamp.",
  }),
  page: pagingNumber(1, 1_000_000).optional(),
  limit: pagingNumber(1, 100).optional(),
});

export const workspaceActivityExportQuery = z.object({
  userId: workspaceActivityQuery.shape.userId,
  type: workspaceActivityQuery.shape.type,
  projectId: workspaceActivityQuery.shape.projectId,
  from: workspaceActivityQuery.shape.from,
  to: workspaceActivityQuery.shape.to,
  format: z.enum(["csv", "json"]).optional().openapi({
    description: 'Export format. Defaults to "csv".',
  }),
});

export const updateWorkspaceActivityRetentionBody = z.object({
  activityRetentionDays: z.number().int().min(0).max(3650).nullable().openapi({
    description:
      "Days of activity history to keep. 0 or null disables retention (keep forever), which is the default. This setting is not currently enforced by any automatic deletion; it is stored for a future opt-in pruning job.",
  }),
});
