import { z } from "../openapi";

export const workspaceIdParam = z.object({ workspaceId: z.string() });

const pagingNumber = (min: number, max: number) =>
  z
    .string()
    .regex(/^\d+$/, "Expected a positive integer")
    .transform(Number)
    .pipe(z.number().int().min(min).max(max));

// Required object of optional filters: a RouteParameter cannot itself be optional.
export const workspaceActivityQuery = z.object({
  userId: z.string().optional().openapi({
    description: "Only activity generated by this user.",
  }),
  type: z.string().optional().openapi({
    description: "Only activity of this type, e.g. status_changed.",
  }),
  from: z.string().optional().openapi({
    description: "Only activity created at or after this ISO timestamp.",
  }),
  to: z.string().optional().openapi({
    description: "Only activity created at or before this ISO timestamp.",
  }),
  page: pagingNumber(1, 1_000_000).optional(),
  limit: pagingNumber(1, 100).optional(),
});
